#pragma once

#define ARM_IRQ_PPI_HP_TIMER   (26)
#define ARM_IRQ_PPI_V_TIMER    (27)
#define ARM_IRQ_PPI_LEGACY_FIQ (28)
#define ARM_IRQ_PPI_PS_TIMER   (29)
#define ARM_IRQ_PPI_PSN_TIMER  (30)
#define ARM_IRQ_PPI_LEGACY_IRQ (28)

#define ARM_IRQ_MAILBOX_BASE (32) // to 47

#define ARM_IRQ_SPI_PMU_CORE0 (48)
#define ARM_IRQ_SPI_PMU_CORE1 (49)
#define ARM_IRQ_SPI_PMU_CORE2 (50)
#define ARM_IRQ_SPI_PMU_CORE3 (51)

#define ARM_IRQ_SPI_AXIERR (52)

#define ARM_IRQ_SPI_LOCAL_TIMER (53)

#define ARM_IRQ_SPI_ARMC_BASE            (64) // to 79
#define ARM_IRQ_SPI_ARMC_TIMER           (ARM_IRQ_SPI_ARMC_BASE + 0)
#define ARM_IRQ_SPI_ARMC_MAILBOX         (ARM_IRQ_SPI_ARMC_BASE + 1)
#define ARM_IRQ_SPI_ARMC_DOORBELL0       (ARM_IRQ_SPI_ARMC_BASE + 2)
#define ARM_IRQ_SPI_ARMC_DOORBELL1       (ARM_IRQ_SPI_ARMC_BASE + 3)
#define ARM_IRQ_SPI_ARMC_VPU0_HALTED     (ARM_IRQ_SPI_ARMC_BASE + 4)
#define ARM_IRQ_SPI_ARMC_VPU1_HALTED     (ARM_IRQ_SPI_ARMC_BASE + 5)
#define ARM_IRQ_SPI_ARMC_ARM_ADDRESS_ERR (ARM_IRQ_SPI_ARMC_BASE + 6)
#define ARM_IRQ_SPI_ARMC_ARM_AXI_ERR     (ARM_IRQ_SPI_ARMC_BASE + 7)
#define ARM_IRQ_SPI_ARMC_SOFT_INT0       (ARM_IRQ_SPI_ARMC_BASE + 8)
#define ARM_IRQ_SPI_ARMC_SOFT_INT1       (ARM_IRQ_SPI_ARMC_BASE + 9)
#define ARM_IRQ_SPI_ARMC_SOFT_INT2       (ARM_IRQ_SPI_ARMC_BASE + 10)
#define ARM_IRQ_SPI_ARMC_SOFT_INT3       (ARM_IRQ_SPI_ARMC_BASE + 11)
#define ARM_IRQ_SPI_ARMC_SOFT_INT4       (ARM_IRQ_SPI_ARMC_BASE + 12)
#define ARM_IRQ_SPI_ARMC_SOFT_INT5       (ARM_IRQ_SPI_ARMC_BASE + 13)
#define ARM_IRQ_SPI_ARMC_SOFT_INT6       (ARM_IRQ_SPI_ARMC_BASE + 14)
#define ARM_IRQ_SPI_ARMC_SOFT_INT7       (ARM_IRQ_SPI_ARMC_BASE + 15)

#define ARM_IRQ_SPI_VC_BASE    (96) // to 159
#define ARM_IRQ_SPI_SYS_TIMER0 (ARM_IRQ_SPI_VC_BASE + 0)
#define ARM_IRQ_SPI_SYS_TIMER1 (ARM_IRQ_SPI_VC_BASE + 1)
#define ARM_IRQ_SPI_SYS_TIMER2 (ARM_IRQ_SPI_VC_BASE + 2)
#define ARM_IRQ_SPI_SYS_TIMER3 (ARM_IRQ_SPI_VC_BASE + 3)

#define ARM_IRQ_SPI_ETH_PCIE_BASE (160) // to 216
